const ADD_TO_CART = "ADD_TO_CART"
const REMOVE_FROM_CART = "REMOVE_FROM_CART"
const CLEAN_CART = "CLEAN_CART"
const INCREMENT_COUNT = "INCREMENT_COUNT"
const DECREMENT_COUNT = "DECREMENT_COUNT"
const INITIALIZE = "INITIALIZE"



export {
    ADD_TO_CART,
    REMOVE_FROM_CART,
    CLEAN_CART,
    INCREMENT_COUNT,
    DECREMENT_COUNT,
    INITIALIZE
}